version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mca-serverless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1grz1etd7aqwj"
s3_prefix = "mca-serverless"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
